import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/page";



const poppins = Poppins({
  weight: ['400', '600'], // Spécifie les poids de la police que tu veux utiliser
  subsets: ['latin'], // Sous-ensemble de caractères (ici, les caractères latins)
  display: 'swap', // Améliore l'affichage de la police
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
